package codex

import (
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	source "github.com/kotokumu/agentmetry/sourceplugin"
)

func TestPlugin_SessionNames(t *testing.T) {
	type args struct {
		event source.Event
	}
	tests := []struct {
		name string
		p    Plugin
		args args
		want []source.SessionName
	}{
		{name: "direct result targets listed ID", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "known wrapper", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "Wall time: 3.0673 seconds\nOutput:\n{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "normalized stored event", args: args{event: source.Event{Name: "gen_ai.tool_result", Attributes: map[string]any{"tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "boolean success", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": true, "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "explicit wrong native event", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.user_prompt", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "nonstring native event", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": 4, "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "wrong namespace", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "other", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "wrong tool", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "read_thread", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "failed result", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "false", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "missing success", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "unknown version", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":5,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "missing version", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "duplicate version", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "duplicate array", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "trailing body", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]} garbage"}}}, want: nil},
		{name: "arbitrary text prefix", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "look here: {\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "negative wall time", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "Wall time: -1 seconds\nOutput:\n{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "nested title not authoritative", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"summary\":{\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}}"}}}, want: nil},
		{name: "mixed kinds and pinned entries", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}],\"threads\":[{\"id\":\"target\",\"kind\":\"chatgpt\",\"title\":\"Wrong\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "duplicate title", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\",\"title\":\"Other\"}]}"}}}, want: nil},
		{name: "duplicate id", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"other\",\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "duplicate kind", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"chatgpt\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "blank id", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\" \",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "blank name", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"  \"}]}"}}}, want: nil},
		{name: "nonstring title", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":4}]}"}}}, want: nil},
		{name: "masked title", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"<redacted>\"}]}"}}}, want: nil},
		{name: "redacted id", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"[REDACTED]\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: nil},
		{name: "preserve exact title", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"  <b>観測</b>  \"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "  <b>観測</b>  ", Origin: "codex_app.list_threads"}}},
		{name: "event time not updatedAt", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "event.timestamp": "2026-09-09T01:02:03.123Z", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\",\"updatedAt\":1}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads", ObservedAt: time.Date(2026, 9, 9, 1, 2, 3, 123000000, time.UTC)}}},
		{name: "invalid time remains unknown", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "event.timestamp": "invalid", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "UTC time out of bounds", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "event.timestamp": "9999-12-31T23:59:59-01:00", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "complete prefix incomplete next item", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output_truncated": true, "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"},{\"id\":\"tail\",\"kind\":\"codex\",\"title\":\"Cut\n[... telemetry preview truncated ...]"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}}},
		{name: "complete ID title but unfinished entry", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output_truncated": true, "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\",\"updatedAt\":123\n[... telemetry preview truncated ...]"}}}, want: nil},
		{name: "truncated no flag", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}\n[... telemetry preview truncated ...]"}}}, want: nil},
		{name: "truncated no marker", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output_truncated": true, "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}"}}}, want: nil},
		{name: "malformed middle is not truncation", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output_truncated": true, "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"},oops\n[... telemetry preview truncated ...]"}}}, want: nil},
		{name: "incomplete version after entries", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output_truncated": true, "output": "{\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"}],\"schemaVersion\":\n[... telemetry preview truncated ...]"}}}, want: nil},
		{name: "duplicate target observations retained", args: args{event: source.Event{Name: "codex.tool_result", Attributes: map[string]any{"event.name": "codex.tool_result", "tool_namespace": "mcp__codex_app", "tool_name": "list_threads", "success": "true", "conversation.id": "executor", "output": "{\"schemaVersion\":4,\"pinnedThreads\":[],\"threads\":[{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Observed\"},{\"id\":\"target\",\"kind\":\"codex\",\"title\":\"Other\"}]}"}}}, want: []source.SessionName{{ConversationID: "target", Text: "Observed", Origin: "codex_app.list_threads"}, {ConversationID: "target", Text: "Other", Origin: "codex_app.list_threads"}}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := Plugin{}
			if got := p.SessionNames(tt.args.event); !cmp.Equal(tt.want, got) {
				t.Errorf("Plugin.SessionNames() = %v, want %v\ndiff=%s", got, tt.want, cmp.Diff(tt.want, got))
			}
		})
	}
}
